on: push
name: Deploy to nashural.ru
jobs:
  deploy-ftp:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v2.3.2
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: nashural.ru
          username: nashur_0
          password: ${{ secrets.ftp_password }}
          local-dir: ./
          server-dir: /tours-api/
